// AUTO-GENERATED by gen_slothy_src.py -- flat, macro-free, cpp-free SLOTHY input.
// doc-2 4-temp schedule (p7). live-in: x16/x17 tables; z0..z25 coeffs; z30=q; p7 ptrue.h. live-out: z0,z1,z2,z3,z4,z7,z16,z17,z18,z19,z20,z21,z22,z23,z24,z25
    .arch armv8-a+sve
    .text

phaseA_start:
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 128, zeta[1], butterflies 0..3
    movprfx z5, z18
    smulh z5.h, p7/m, z5.h, z28.h
    movprfx z6, z19
    smulh z6.h, p7/m, z6.h, z28.h
    movprfx z26, z20
    smulh z26.h, p7/m, z26.h, z28.h
    movprfx z27, z21
    smulh z27.h, p7/m, z27.h, z28.h
    mul z18.h, p7/m, z18.h, z29.h
    mul z19.h, p7/m, z19.h, z29.h
    mul z20.h, p7/m, z20.h, z29.h
    mul z21.h, p7/m, z21.h, z29.h
    smulh z18.h, p7/m, z18.h, z30.h
    smulh z19.h, p7/m, z19.h, z30.h
    smulh z20.h, p7/m, z20.h, z30.h
    smulh z21.h, p7/m, z21.h, z30.h
    sub z5.h, z5.h, z18.h
    sub z6.h, z6.h, z19.h
    sub z26.h, z26.h, z20.h
    sub z27.h, z27.h, z21.h
    sub z18.h, z0.h, z5.h
    sub z19.h, z1.h, z6.h
    sub z20.h, z2.h, z26.h
    sub z21.h, z3.h, z27.h
    add z0.h, z0.h, z5.h
    add z1.h, z1.h, z6.h
    add z2.h, z2.h, z26.h
    add z3.h, z3.h, z27.h
    // len = 128, zeta[1], butterflies 4..7
    movprfx z5, z22
    smulh z5.h, p7/m, z5.h, z28.h
    movprfx z6, z23
    smulh z6.h, p7/m, z6.h, z28.h
    movprfx z26, z24
    smulh z26.h, p7/m, z26.h, z28.h
    movprfx z27, z25
    smulh z27.h, p7/m, z27.h, z28.h
    mul z22.h, p7/m, z22.h, z29.h
    mul z23.h, p7/m, z23.h, z29.h
    mul z24.h, p7/m, z24.h, z29.h
    mul z25.h, p7/m, z25.h, z29.h
    smulh z22.h, p7/m, z22.h, z30.h
    smulh z23.h, p7/m, z23.h, z30.h
    smulh z24.h, p7/m, z24.h, z30.h
    smulh z25.h, p7/m, z25.h, z30.h
    sub z5.h, z5.h, z22.h
    sub z6.h, z6.h, z23.h
    sub z26.h, z26.h, z24.h
    sub z27.h, z27.h, z25.h
    sub z22.h, z4.h, z5.h
    sub z23.h, z7.h, z6.h
    sub z24.h, z16.h, z26.h
    sub z25.h, z17.h, z27.h
    add z4.h, z4.h, z5.h
    add z7.h, z7.h, z6.h
    add z16.h, z16.h, z26.h
    add z17.h, z17.h, z27.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 64, zeta[2]
    movprfx z5, z4
    smulh z5.h, p7/m, z5.h, z28.h
    movprfx z6, z7
    smulh z6.h, p7/m, z6.h, z28.h
    movprfx z26, z16
    smulh z26.h, p7/m, z26.h, z28.h
    movprfx z27, z17
    smulh z27.h, p7/m, z27.h, z28.h
    mul z4.h, p7/m, z4.h, z29.h
    mul z7.h, p7/m, z7.h, z29.h
    mul z16.h, p7/m, z16.h, z29.h
    mul z17.h, p7/m, z17.h, z29.h
    smulh z4.h, p7/m, z4.h, z30.h
    smulh z7.h, p7/m, z7.h, z30.h
    smulh z16.h, p7/m, z16.h, z30.h
    smulh z17.h, p7/m, z17.h, z30.h
    sub z5.h, z5.h, z4.h
    sub z6.h, z6.h, z7.h
    sub z26.h, z26.h, z16.h
    sub z27.h, z27.h, z17.h
    sub z4.h, z0.h, z5.h
    sub z7.h, z1.h, z6.h
    sub z16.h, z2.h, z26.h
    sub z17.h, z3.h, z27.h
    add z0.h, z0.h, z5.h
    add z1.h, z1.h, z6.h
    add z2.h, z2.h, z26.h
    add z3.h, z3.h, z27.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 64, zeta[3]
    movprfx z5, z22
    smulh z5.h, p7/m, z5.h, z28.h
    movprfx z6, z23
    smulh z6.h, p7/m, z6.h, z28.h
    movprfx z26, z24
    smulh z26.h, p7/m, z26.h, z28.h
    movprfx z27, z25
    smulh z27.h, p7/m, z27.h, z28.h
    mul z22.h, p7/m, z22.h, z29.h
    mul z23.h, p7/m, z23.h, z29.h
    mul z24.h, p7/m, z24.h, z29.h
    mul z25.h, p7/m, z25.h, z29.h
    smulh z22.h, p7/m, z22.h, z30.h
    smulh z23.h, p7/m, z23.h, z30.h
    smulh z24.h, p7/m, z24.h, z30.h
    smulh z25.h, p7/m, z25.h, z30.h
    sub z5.h, z5.h, z22.h
    sub z6.h, z6.h, z23.h
    sub z26.h, z26.h, z24.h
    sub z27.h, z27.h, z25.h
    sub z22.h, z18.h, z5.h
    sub z23.h, z19.h, z6.h
    sub z24.h, z20.h, z26.h
    sub z25.h, z21.h, z27.h
    add z18.h, z18.h, z5.h
    add z19.h, z19.h, z6.h
    add z20.h, z20.h, z26.h
    add z21.h, z21.h, z27.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 32, zeta[4]
    movprfx z5, z2
    smulh z5.h, p7/m, z5.h, z28.h
    movprfx z6, z3
    smulh z6.h, p7/m, z6.h, z28.h
    mul z2.h, p7/m, z2.h, z29.h
    mul z3.h, p7/m, z3.h, z29.h
    smulh z2.h, p7/m, z2.h, z30.h
    smulh z3.h, p7/m, z3.h, z30.h
    sub z5.h, z5.h, z2.h
    sub z6.h, z6.h, z3.h
    sub z2.h, z0.h, z5.h
    sub z3.h, z1.h, z6.h
    add z0.h, z0.h, z5.h
    add z1.h, z1.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 32, zeta[5]
    movprfx z5, z16
    smulh z5.h, p7/m, z5.h, z28.h
    movprfx z6, z17
    smulh z6.h, p7/m, z6.h, z28.h
    mul z16.h, p7/m, z16.h, z29.h
    mul z17.h, p7/m, z17.h, z29.h
    smulh z16.h, p7/m, z16.h, z30.h
    smulh z17.h, p7/m, z17.h, z30.h
    sub z5.h, z5.h, z16.h
    sub z6.h, z6.h, z17.h
    sub z16.h, z4.h, z5.h
    sub z17.h, z7.h, z6.h
    add z4.h, z4.h, z5.h
    add z7.h, z7.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 32, zeta[6]
    movprfx z5, z20
    smulh z5.h, p7/m, z5.h, z28.h
    movprfx z6, z21
    smulh z6.h, p7/m, z6.h, z28.h
    mul z20.h, p7/m, z20.h, z29.h
    mul z21.h, p7/m, z21.h, z29.h
    smulh z20.h, p7/m, z20.h, z30.h
    smulh z21.h, p7/m, z21.h, z30.h
    sub z5.h, z5.h, z20.h
    sub z6.h, z6.h, z21.h
    sub z20.h, z18.h, z5.h
    sub z21.h, z19.h, z6.h
    add z18.h, z18.h, z5.h
    add z19.h, z19.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 32, zeta[7]
    movprfx z5, z24
    smulh z5.h, p7/m, z5.h, z28.h
    movprfx z6, z25
    smulh z6.h, p7/m, z6.h, z28.h
    mul z24.h, p7/m, z24.h, z29.h
    mul z25.h, p7/m, z25.h, z29.h
    smulh z24.h, p7/m, z24.h, z30.h
    smulh z25.h, p7/m, z25.h, z30.h
    sub z5.h, z5.h, z24.h
    sub z6.h, z6.h, z25.h
    sub z24.h, z22.h, z5.h
    sub z25.h, z23.h, z6.h
    add z22.h, z22.h, z5.h
    add z23.h, z23.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 16, zeta[8]
    movprfx z6, z1
    smulh z6.h, p7/m, z6.h, z28.h
    mul z1.h, p7/m, z1.h, z29.h
    smulh z1.h, p7/m, z1.h, z30.h
    sub z6.h, z6.h, z1.h
    sub z1.h, z0.h, z6.h
    add z0.h, z0.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 16, zeta[9]
    movprfx z6, z3
    smulh z6.h, p7/m, z6.h, z28.h
    mul z3.h, p7/m, z3.h, z29.h
    smulh z3.h, p7/m, z3.h, z30.h
    sub z6.h, z6.h, z3.h
    sub z3.h, z2.h, z6.h
    add z2.h, z2.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 16, zeta[10]
    movprfx z6, z7
    smulh z6.h, p7/m, z6.h, z28.h
    mul z7.h, p7/m, z7.h, z29.h
    smulh z7.h, p7/m, z7.h, z30.h
    sub z6.h, z6.h, z7.h
    sub z7.h, z4.h, z6.h
    add z4.h, z4.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 16, zeta[11]
    movprfx z6, z17
    smulh z6.h, p7/m, z6.h, z28.h
    mul z17.h, p7/m, z17.h, z29.h
    smulh z17.h, p7/m, z17.h, z30.h
    sub z6.h, z6.h, z17.h
    sub z17.h, z16.h, z6.h
    add z16.h, z16.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 16, zeta[12]
    movprfx z6, z19
    smulh z6.h, p7/m, z6.h, z28.h
    mul z19.h, p7/m, z19.h, z29.h
    smulh z19.h, p7/m, z19.h, z30.h
    sub z6.h, z6.h, z19.h
    sub z19.h, z18.h, z6.h
    add z18.h, z18.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 16, zeta[13]
    movprfx z6, z21
    smulh z6.h, p7/m, z6.h, z28.h
    mul z21.h, p7/m, z21.h, z29.h
    smulh z21.h, p7/m, z21.h, z30.h
    sub z6.h, z6.h, z21.h
    sub z21.h, z20.h, z6.h
    add z20.h, z20.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 16, zeta[14]
    movprfx z6, z23
    smulh z6.h, p7/m, z6.h, z28.h
    mul z23.h, p7/m, z23.h, z29.h
    smulh z23.h, p7/m, z23.h, z30.h
    sub z6.h, z6.h, z23.h
    sub z23.h, z22.h, z6.h
    add z22.h, z22.h, z6.h
    ld1rh   {z28.h}, p7/z, [x16]
    ld1rh   {z29.h}, p7/z, [x17]
    add     x16, x16, #2
    add     x17, x17, #2
    // len = 16, zeta[15]
    movprfx z6, z25
    smulh z6.h, p7/m, z6.h, z28.h
    mul z25.h, p7/m, z25.h, z29.h
    smulh z25.h, p7/m, z25.h, z30.h
    sub z6.h, z6.h, z25.h
    sub z25.h, z24.h, z6.h
    add z24.h, z24.h, z6.h
phaseA_end: